// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package chat_app

type LoginInput struct {
	Name string `json:"name"`
}

type NewMessage struct {
	Text   string `json:"text"`
	UserID int    `json:"userId"`
	RoomID int    `json:"roomId"`
}

type NewParticipation struct {
	UserID int `json:"userID"`
	RoomID int `json:"roomID"`
}

type NewRoom struct {
	UserID int    `json:"userID"`
	Name   string `json:"name"`
}

type NewUser struct {
	Name string `json:"name"`
}
